### ISSUE TITLE
Make explicit how rotation can drive 2 columns -> 3 columns

### ISSUE THREAD

**Issue by fatuhoku** [adamwaite/SelfSizingWaterfallCollectionViewLayout#1]
The example project does not behave shown in the GIF in this respect!

**Comment by adamwaite** [comment]
The example works with size classes, should be good to go on iPhone 6 Plus and iPads. Either that or you've got the old classic portrait orientation lock on mistake?! Let me know.

**Comment by fatuhoku** [comment]
@adamwaite Ah. I've not read up on size classes so that's probably why I'm blind to it. I can check what I ran this on...
